# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goods.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgoods.proto\x12\x05goods\"E\n\x05Goods\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\"\x15\n\x07GoodsId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x63\n\tGoodsInfo\x12(\n\x08\x61\x64\x64Goods\x12\x0c.goods.Goods\x1a\x0e.goods.GoodsId\x12,\n\x0cgetGoodsById\x12\x0e.goods.GoodsId\x1a\x0c.goods.GoodsB\x1e\n\x0e\x63om.sora.protoB\nGoodsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'goods_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.sora.protoB\nGoodsProtoP\001'
  _globals['_GOODS']._serialized_start=22
  _globals['_GOODS']._serialized_end=91
  _globals['_GOODSID']._serialized_start=93
  _globals['_GOODSID']._serialized_end=114
  _globals['_GOODSINFO']._serialized_start=116
  _globals['_GOODSINFO']._serialized_end=215
# @@protoc_insertion_point(module_scope)
